### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by Nugwxa** [Nugwxa/cravezy#3]
## Task

- [x] Create a form with fields for email and password
- [x] Implement client side validation
- [x] Handle form submission with appropriate error handling
- [x] Redirect to the homepage or the `redirect` query param value(If present) after login

## The Design

![image](https://github.com/user-attachments/assets/c0368b9e-f2c7-406f-a526-13e65bd2e55f)
