### ISSUE TITLE
Create registration route

### ISSUE THREAD

**Issue by Nugwxa** [Nugwxa/cravezy#4]
## Task

- [ ] Create a form with fields for email, password, password confirmation, and verification code
- [ ] Implement client side validation
- [ ] Handle form submission with appropriate error handling
- [ ] #9
- [ ] Redirect to the homepage or the `redirect` query param value(If present) after account creation

## The Design

![image](https://github.com/user-attachments/assets/75034834-11b2-4af6-9311-be494ee34b97)
