### ISSUE TITLE
Create Forgot Password Page

### ISSUE THREAD

**Issue by Nugwxa** [Nugwxa/cravezy#5]
## Task

- [x] Create a form with an email field
- [x] Implement client side validation
- [x] Handle form submission with appropriate error handling

## The Design

![image](https://github.com/user-attachments/assets/ab1ebc8e-6483-40e4-8a4f-7a9fc50f8b6e)
